map_server:
  ros__parameters:
    yaml_filename: "test_map.yaml"
DwbController:
  ros__parameters:
    debug_trajectory_details: True
    min_vel_x: -0.26
    min_vel_y: 0.0
    max_vel_x: 0.26
    max_vel_y: 0.0
    max_vel_theta: 1.0
    min_speed_xy: 0.0
    # Set max XY speed to a large value so noisy Y data from IMU doesn't
    # prevent operation. Since this robot has no Y velocity capability, any Y
    # velocity reported in /odom data is due to slippage or noise, and there is
    # no need to reduce the robot's operating envelope when generating possible
    # trajectories.
    max_speed_xy: 100.0
    min_speed_theta: 0.0
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
    vx_samples: 5
    vy_samples: 5
    vtheta_samples: 5
    sim_time: 1.7
    linear_granularity: 0.025
    xy_goal_tolerance: 0.25
    ObstacleFootprint.scale: 0.1
    ObstacleFootprint.max_scaling_factor: 0.2
    ObstacleFootprint.scaling_speed: 0.25
    PathAlign.scale: 40.0
    PathAlign.aggregation_type: last
    GoalAlign.scale: 20.0
    GoalAlign.aggregation_type: last
    PathDist.scale: 50.0
    PathDist.aggregation_type: last
    GoalDist.scale: 30.0
    GoalDist.aggregation_type: last
    RotateToGoal.scale: 32.0
    Oscillation.scale: 0.0
local_costmap:
  local_costmap:
    ros__parameters:
      robot_radius: 0.13
      inflation_layer.cost_scaling_factor: 2.0
      global_frame: base_link
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
global_costmap:
  global_costmap:
    ros__parameters:
      robot_radius: 0.17
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
